PACKAGE = test_minhash_classfier
SRCS = test_minhash_classifier.cpp test_minhash_multi_classifier.cpp
HEADS =  ../include/array.hpp ../include/minhash.hpp ../include/minhash_classifier.hpp ../include/minhash_multi_classifier.hpp
OBJS = $(SRCS:.cpp=.o)

LD = g++
LDLIBS = -llog4cxx

CXX = g++
CXXFLAGS = -g -Wall -I../include

run: $(PACKAGE)
	./$(PACKAGE)

$(PACKAGE): $(OBJS)
	$(LD) $(LDFLAGS) $(OBJS) -o $@ $(LDLIBS)

$(OBJS): $(HEADS) makefile

.cpp.o:
	$(CXX) $(CXXFLAGS) -c $< -o $@

clean:
	rm -f $(PACKAGE) $(OBJS)
